# .github/workflows/test.yaml
name: test
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WORKSPACE: /github/workspace/
      CI_SYSTEM: github
      # the env vars for the PostgreSQL connection must be in sync
      # with the 'postgres' service below
      PGHOST: postgres
      PGDATABASE: migratum
      PGUSER: migratum
      PGPASSWORD: FvbRd5qdeWHNum9p
      QUICKLISP_DIST_VERSION: latest
      QUICKLISP_ADD_TO_INIT_FILE: true
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub PostgreSQL image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: migratum
          POSTGRES_PASSWORD: FvbRd5qdeWHNum9p
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Test
        uses: docker://clfoundation/sbcl:2.2.4
        with:
          args: /github/workspace/scripts/run-ci-tests.sh
